M48
; DRILL file {KiCad 9.0.5} date 2025-11-01T11:44:51+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-01T11:44:51+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,3,4,Blind
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,Buried,ViaDrill
T1C0.300
%
G90
G05
T1
X122.5Y-41.696
X157.298Y-64.696
X163.267Y-40.734
X163.267Y-42.004
M30
